steps:
  # Docker Build
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - "."
      - -t
      - gcr.io/$PROJECT_ID/react-chat-app:$TAG_NAME
      - --build-arg
      - REACT_APP_API_KEY=$_REACT_APP_API_KEY
      - --build-arg
      - REACT_APP_AUTH_DOMAIN=$_REACT_APP_AUTH_DOMAIN
      - --build-arg 
      - REACT_APP_PROJECT_ID=$_REACT_APP_PROJECT_ID
      - --build-arg 
      - REACT_APP_STORAGE_BUCKET=$_REACT_APP_STORAGE_BUCKET
      - --build-arg
      - REACT_APP_MESSAGING_SENDER_ID=$_REACT_APP_MESSAGING_SENDER_ID
      - --build-arg 
      - REACT_APP_APP_ID=$_REACT_APP_APP_ID
      - --build-arg
      - REACT_APP_MEASUREMENT_ID=$_REACT_APP_MEASUREMENT_ID

  # Docker Push
  - name: "gcr.io/cloud-builders/docker"
    args:
      - push
      - gcr.io/$PROJECT_ID/react-chat-app:$TAG_NAME

  # Deploy container image to GKE
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=deployment.yaml
      - --image=gcr.io/$PROJECT_ID/react-chat-app:$TAG_NAME
      - --location=$_CLUSTER_LOCATION
      - --cluster=$_CLUSTER_NAME
      - --project=$PROJECT_ID

