apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: react-chat-app
  name: react-chat-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-chat-app
  template:
    metadata:
      labels:
        app: react-chat-app
    spec:
      containers:
          # Update with correct project name
        - image: gcr.io/final-346218/react-chat-app:latest
          imagePullPolicy: Always
          name: react-chat-app
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: react-chat-app
  name: react-chat-app-hpa
spec:
  maxReplicas: 5
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 80
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: react-chat-app

---
apiVersion: "networking.k8s.io/v1"
kind: Ingress
metadata:
  name: react-chat-app-ingress
  annotations:
    # Update with a certificate name
    networking.gke.io/managed-certificates: "680-chat-app-cert"
    # Update with static ip name
    networking.gke.io/static-ip: "chat-app-ip"
spec:
  defaultBackend:
    service:
      name: nginx-react-chat-app-load-balancer
      port:
        number: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-react-chat-app-load-balancer
  labels:
    app: react-chat-app
    app.kubernetes.io/managed-by: gcp-cloud-build-deploy
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: react-chat-app
  type: LoadBalancer
  loadBalancerIP: ""
